version: "3.7"

x-djangoapi:

services:
  traefik:
    restart: always
    image: traefik
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS:certs/localhost_https_localhost.crt,certs/localhost_https_localhost.key"
      - "--defaultentrypoints=http,https"
      - "--docker"
      - "--docker.watch"
    volumes:
      - ./certs/:/certs/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
     - "80:80"
     - "443:443"
     - "3001:3001"
     - "8080:8080"
  djangoapi:
    build:
      target: dev
      context: .
      dockerfile: docker/django/Dockerfile
    image: djangoapi_dev:latest
    volumes:
      &djangoapi-volumes
      - ./djangoapi:/code/djangoapi
      - ./runserver.py:/code/runserver.py
      - ./manage.py:/code/manage.py
      - ./:/tmpdb
    labels:
      - "traefik.enable=true"
      - "traefik.port=3002"
      - "traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-Proto:https"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/graphql,/admin,/django-static"
    environment:
      &djangoapi-environment
      DEBUG: "True"
      ALLOWED_HOSTS: "djangoapi,localhost"
      DOMAIN: "localhost"
      SITE_NAME: "My Site"
      PROXY_SSL: "True"
      SECRET_KEY: "u079tk=6$$!hcrr4%yb1!a7+3ycg0=4-nudet6+8w)f-)24j-j4"
      EMAIL_URL: ${EMAIL_URL:-consolemail://}
      SOCIAL_AUTH_GITHUB_KEY: ${SOCIAL_AUTH_GITHUB_KEY}
      SOCIAL_AUTH_GITHUB_SECRET: ${SOCIAL_AUTH_GITHUB_SECRET}

  djangoapiwatch:
    build:
      target: dev
      context: .
      dockerfile: docker/django/Dockerfile
    image: djangoapi_dev:latest
    volumes: *djangoapi-volumes
    environment: *djangoapi-environment
    command: python manage.py graphql_schema --watch

  reactapp:
    build:
      target: dev
      context: .
      dockerfile: docker/react/Dockerfile
    image: reactapp_dev:latest
    volumes:
      - ./src:/code/src
      - ./public:/code/public
      - ./razzle.config.js:/code/razzle.config.js
      - ./.babelrc:/code/.babelrc
      - ./.eslintrc.js:/code/.eslintrc.js
      - ./customDevClientPort.diff:/code/customDevClientPort.diff
    labels:
      - "traefik.enable=true"
      - "traefik.static.port=3001"
      - "traefik.static.frontend.rule=Host:localhost;PathPrefix:/static,/sockjs-node"
      - "traefik.server.port=3000"
      - "traefik.server.frontend.rule=Host:localhost;PathPrefix:/"
    environment:
      RAZZLE_HOTCLIENT_NOPORT: "true"
      PORT: 3000
      PUBLIC_PATH: https://localhost/
      CLIENT_PUBLIC_PATH: https://localhost/
      GRAPHQL_BACKEND_URL: http://djangoapi:3002/graphql
      GRAPHQL_FRONTEND_URL: https://localhost/graphql
      SINGLE_CHUNK: 1
