version: "3.7"

services:
  traefik:
    restart: always
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
     - "80:80"
     - "443:443"
  djangoapi:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
  reactapp:
    build:
      context: .
      dockerfile: docker/react/Dockerfile