version: "3.7"

services:
  djangoapi:
    build:
      target: prod
      context: .
      dockerfile: docker/django/Dockerfile
    image: djangoapi:latest
    labels:
      - "traefik.enable=true"
      - "traefik.port=3002"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/api,/admin"
      - "traefik.network=traefik"
    networks:
      - traefik
  reactapp:
    build:
      target: prod
      context: .
      dockerfile: docker/react/Dockerfile
      args:
        PUBLIC_PATH: https://localhost/
        CLIENT_PUBLIC_PATH: https://localhost/
    image: reactapp:latest
    labels:
      - "traefik.enable=true"
      - "traefik.server.port=3000"
      - "traefik.server.frontend.rule=Host:localhost"
      - "traefik.network=traefik"
    networks:
      - traefik


networks:
  traefik:
    external:
      name: traefik