version: "3.7"

services:
  traefik:
    restart: always
    image: traefik
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS:certs/localhost_https_localhost.crt,certs/localhost_https_localhost.key"
      - "--entrypoints=Name:httpsdev Address::3001 TLS:certs/localhost_https_localhost.crt,certs/localhost_https_localhost.key"
      - "--defaultentrypoints=http,https,httpsdev"
      - "--docker"
      - "--docker.watch"
    volumes:
      - ./certs/:/certs/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
     - "80:80"
     - "443:443"
     - "3001:3001"
  djangoapi:
    build:
      target: dev
      context: .
      dockerfile: docker/django/Dockerfile
    image: djangoapi_dev:latest
    volumes:
      - ./djangoapi:/code/djangoapi
      - ./runserver.py:/code/runserver.py
      - ./manage.py:/code/manage.py
      - ./db.sqlite3:/code/db.sqlite3
    labels:
      - "traefik.enable=true"
      - "traefik.port=3002"
      - "traefik.frontend.headers.customRequestHeaders=X-Forwarded-Proto:https"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/graphql,/admin"
  reactapp:
    build:
      target: dev
      context: .
      dockerfile: docker/react/Dockerfile
    image: reactapp_dev:latest
    volumes:
      - ./src:/code/src
      - ./public:/code/public
      - ./razzle-plugins:/code/razzle-plugins
      - ./.securityrc.js:/code/.securityrc.js
      - ./razzle.config.js:/code/razzle.config.js
      - ./.babelrc:/code/.babelrc
    labels:
      - "traefik.enable=true"
      - "traefik.server.port=3000"
      - "traefik.server.frontend.rule=Host:localhost"
      - "traefik.static.port=3001"
      - "traefik.static.frontend.rule=Host:localhost;PathPrefix:/static,/sockjs-node"
    environment:
      PUBLIC_PATH: https://localhost/
      CLIENT_PUBLIC_PATH: https://localhost/
      RAZZLE_API_URI: https://localhost/graphql
